### PR TITLE
#1: Rather than raising a `SignalException`, sigurd will now call `ex…

### PR DESCRIPTION
**Pull request by dorner**
…it 0` after shutdown

### CODE REVIEW

**Review by iMacTia — APPROVED** [review]
TIL `SystemExit` 🎉 !

@dorner this looks great and it's perfectly OK to introduce the breaking change since we're under v1.0, but are you sure you wouldn't prefer to default the new `stay_alive_on_signal` to `true` to mimick the existing behaviour?

If we wanted to try the change in our application, we still couldn't without first upgrading `deimos` since it has `sigurd ~> 0.0.1` in its gemspec.
That means you'll need to relax the sigurd version in `deimos` gemspec, but that will cause the breaking behaviour to affect unaware developers.

We should be doing this only if we're 100% sure this is the right way to do things and won't break the environment for people running on EC2 instances or other infrastructure types

**Comment by dorner** [comment]
heh I keep assuming we're the only ones using this library, although I guess technically it's possible someone else is and hasn't told me. :D I was hoping to avoid updating Deimos but forgot that we pinned the version. Since we have to update it anyway, it probably can't hurt to leave the default behavior as is and update Deimos to change it 👍

**Comment by dorner** [comment]
@iMacTia updated!

**Comment by iMacTia** [comment]
Awesome 🙌 ! You'll need to update the documentation though as it's still referring to `stay_alive_on_signal`

**Comment by iMacTia** [comment]
Thank you @dorner 💯🎉!

This is just a sidenote, because I don't really want to make this any more complicated 🙈, but since the new configuration is a global setting on the `Sigurd` gem, we should probably *not* explicitly set it on `deimos`.

This is because if other gems are using `Sigurd` under the hood, they'd be affected as well when pulled in the same project as `deimos`.
Instead, we should rely on the "host" application setting the flag to their liking or allow to override it at the runner/signal_handler level to avoid conflicts.

Again, we could just pretend this is not an issue based on the assumption `deimos` is the only library using this gem 😄, but I thought it would be good to raise this just in case 👍

**Comment by dorner** [comment]
Yeah - I'd like to keep it simple and leave that assumption that it's not being used *both* with Deimos *and* for some other purpose in the same application. :) We can always revisit when someone complains 😄

**Pull request merged**
